[package]
name = "hickory-dns-test"
version = "0.1.0"
edition = "2021"

[dependencies]
hickory-resolver = { version = "0.24", features = ["dns-over-rustls", "dnssec-ring"] }
tokio = { version = "1", features = ["full"] }
