name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix with Garnix substituter
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            substituters = https://cache.garnix.io https://cache.nixos.org
            trusted-substituters = https://cache.garnix.io https://cache.nixos.org
            # Replace the key below with the actual public key from Garnix
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Build flake
        run: nix build

      - name: Verify static binary
        run: |
          ldd ./result/bin/hickory-dns-test || echo "Static binary verified!"
          file ./result/bin/hickory-dns-test

      - name: Rename binary for release
        run: |
          mkdir -p release
          cp ./result/bin/hickory-dns-test release/hickory-dns-test-x86_64-linux

      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
                  && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                  && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt-get update \
            && sudo apt-get install gh -y
          sudo apt-get update
          sudo apt-get install gh

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" release/hickory-dns-test-x86_64-linux \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release based on cached binary"
