name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix with Garnix substituter
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            substituters = https://cache.garnix.io https://cache.nixos.org
            trusted-substituters = https://cache.garnix.io https://cache.nixos.org
            # Replace the key below with the actual public key from Garnix
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Build flake
        run: nix build

      - name: Verify static binary
        run: |
          ldd ./result/bin/hickory-dns-test || echo "Static binary verified!"
          file ./result/bin/hickory-dns-test

      - name: Rename binary for release
        run: |
          mkdir -p release
          cp ./result/bin/hickory-dns-test release/hickory-dns-test-x86_64-linux

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" release/hickory-dns-test-x86_64-linux \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release based on cached binary"
