name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      
      - name: Build flake
        run: nix build
      
      - name: Verify static binary
        run: |
          ldd ./result/bin/hickory-dns-test || echo "Static binary verified!"
          file ./result/bin/hickory-dns-test
      
      - name: Rename binary for release
        run: |
          mkdir -p release
          cp ./result/bin/hickory-dns-test release/hickory-dns-test-x86_64-linux
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      
      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/hickory-dns-test-x86_64-linux
          asset_name: hickory-dns-test-x86_64-linux
          asset_content_type: application/octet-stream